DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

blog/urls.py
from django.urls import path,re_path,include


from .views import IndexView,PostView,CategoryView,ArchiveView


app_name = 'blog'
urlpatterns = [
    re_path('post/(?P<post_id>\d+)/',PostView.as_view(),name='post'),
    re_path(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', ArchiveView.as_view(), name='archives'),
    re_path('category/(?P<category_id>\d+)/',CategoryView.as_view(),name='category'),

]

comments/urls.py
from django.urls import path,include,re_path

from comments.views import PostCommentsView


app_name = 'comments'
urlpatterns = [
    re_path(r'^post/(?P<post_id>[0-9]+)/$', PostCommentsView.as_view(), name='post_comment'),
]

untitled/urls.py
# from django.contrib import admin
from django.views.static import serve  #处理文件的视图

import xadmin
from django.urls import path,include,re_path
from untitled.settings import MEDIA_ROOT

from blog.views import IndexView

urlpatterns = [
    path('xadmin/', xadmin.site.urls),

    #首页
    path('', IndexView.as_view(), name='index'),

    #博客页面
    path('blog/',include('blog.urls',namespace='blog')),

    #博客评论
    path('comments/',include('comments.urls',namespace='comments')),

    # 配置富文本编辑url
    path('ueditor/', include('DjangoUeditor.urls')),

    # 处理图片显示的url,使用Django自带serve,传入参数告诉它去哪个路径找，我们有配置好的路径MEDIAROOT
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
]

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/archiveindex.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    {% for post in port_list %}
                 <article class="post post-{{ forloop.counter }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blog:post' post.id %}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author.username }}</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% endfor %}




                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">

{#                        <ul class="pagelist">#}
{#                            {% if post_list.has_previous %}#}
{#                                <li class="long"><a href="?{{ post_list.previous_page_number.querystring }}">上一页</a></li>#}
{#                            {% endif %}#}
{##}
{#                            {% for page in post_list.pages %}#}
{#                                {% if page %}#}
{#                                    {% ifequal page post_list.number %}#}
{#                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>#}
{#                                    {% else %}#}
{#                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>#}
{#                                    {% endifequal %}#}
{#                                {% else %}#}
{#                                    <li class="none"><a href="">...</a></li>#}
{#                                {% endif %}#}
{#                            {% endfor %}#}
{#                            {% if post_list.has_next %}#}
{#                                <li class="long"><a href="?{{ post_list.next_page_number.querystring }}">下一页</a></li>#}
{#                            {% endif %}#}
{#                        </ul>#}

                </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">龙小帅的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
               {% block content %}
                {% endblock %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% get_recent_ports as recent_ports %}
                        {% for port in recent_ports %}
                        <li>
                            <a href="{% url 'blog:post' port.id %}">{{ port.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% archives as data_list %}
                        {% for data in data_list %}
                        <li>
                            <a href="{% url 'blog:archives' data.year data.month %}">{{ data.year }} 年 {{ data.month }} 月</a>
                        </li>

                    {% empty %}
                暂无归档！
                {% endfor %}


                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% get_categories as categories %}
                        {% for category in categories %}
                         <li>
                            <a href="{% url 'blog:category' category.id %}">{{ category.name }} <span class="post-count">(13)</span></a>
                        </li>
                        {% endfor %}



                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">龙小帅的博客</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'index' %}">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <article class="post post-{{ post.id }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ post.create_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author.username }}</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">

                        {% autoescape off %}
                        {{ post.body }}
                        {% endautoescape %}
                    </div>
                </article>
    <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                   <form action="{% url 'comments:post_comment' post.id %}" method="post" class="comment-form">
                {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                            <label for="{{ form.name.id_for_label }}">名字：</label>
                         {{ form.name }}
                            {{ form.name.errors }}
                        </div>
                             <div class="col-md-4">
                             <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                                </div>
                                <div class="col-md-4">
                                   <label for="{{ form.url.id_for_label }}">URL：</label>
                                 {{ form.url }}
                                    {{ form.url.errors }}
                                </div>
                                <div class="col-md-12">
                                  <label for="{{ form.text.id_for_label }}">评论：</label>
                                  {{ form.text }}
                                  {{ form.text.errors }}
                                  <button type="submit" class="comment-btn">发表</button>
                                </div>
                              </div>    <!-- row -->
</form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span> {{ comment_list.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                             <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% endfor %}



                        </ul>
                    </div>
                </section>
{% endblock %}

{% block toc %}
    <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <ul>
                        <li>
                            <a href="#">教程特点</a>
                        </li>
                        <li>
                            <a href="#">谁适合这个教程</a>
                        </li>
                        <li>
                            <a href="#">在线预览</a>
                        </li>
                        <li>
                            <a href="#">资源列表</a>
                        </li>
                        <li>
                            <a href="#">获取帮助</a>
                        </li>
                    </ul>
                </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    {% for post in post_list %}
                 <article class="post post-{{ forloop.counter }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blog:post' post.id %}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author.username }}</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% endfor %}




                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">

{#                        <ul class="pagelist">#}
{#                            {% if post_list.has_previous %}#}
{#                                <li class="long"><a href="?{{ post_list.previous_page_number.querystring }}">上一页</a></li>#}
{#                            {% endif %}#}
{##}
{#                            {% for page in post_list.pages %}#}
{#                                {% if page %}#}
{#                                    {% ifequal page post_list.number %}#}
{#                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>#}
{#                                    {% else %}#}
{#                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>#}
{#                                    {% endifequal %}#}
{#                                {% else %}#}
{#                                    <li class="none"><a href="">...</a></li>#}
{#                                {% endif %}#}
{#                            {% endfor %}#}
{#                            {% if post_list.has_next %}#}
{#                                <li class="long"><a href="?{{ post_list.next_page_number.querystring }}">下一页</a></li>#}
{#                            {% endif %}#}
{#                        </ul>#}

                </div>
{% endblock %}

templates/index_time.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for port in port_list %}
    {{ port.title }}
{% endfor %}

</body>
</html>